[workspace]

members = [
    "bootloader",
    "kernel",
    "common",
    "vgafontconverter"
]

[profile.release]
debug = true

[patch.crates-io]
uefi = { git = "https://github.com/rust-osdev/uefi-rs", features = ["alloc", "logger", "exts"] }
